# Generated by Django 5.2.3 on 2025-06-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_tags_post_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
